management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    shutdown:
      enabled: true
    info:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
