version: '3'
services:
  backend:
    build:
      context: game-session-service
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/games_service
      SPRING_DATASOURCE_USERNAME: games_service
      SPRING_DATASOURCE_PASSWORD: games_service_passwd
  database:
      image: postgres:14-alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=games_service_passwd
        - POSTGRES_USER=games_service
        - POSTGRES_DB=games_service
  frontend:
    build:
      context: mancala-frontend
      dockerfile: ../docker/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8081:8081"